# Generated by Django 4.1.2 on 2022-11-07 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="todo",
            old_name="active",
            new_name="is_active",
        ),
    ]
