# Generated by Django 4.1.2 on 2022-11-09 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0002_rename_active_todo_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="name",
            field=models.CharField(max_length=256, unique=True, verbose_name="Name"),
        ),
    ]
