# Generated by Django 4.1.2 on 2022-11-11 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0003_alter_project_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
    ]
