# Generated by Django 4.1.2 on 2022-11-11 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0004_todo_deleted"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="todo",
            name="deleted",
        ),
    ]
